name: Testing

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  node:
    name: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Testing
      run: wasm-pack test --node